### ISSUE TITLE
KeyError: 'mymap' when trying to save plot using a colormap

### ISSUE THREAD

**Issue by Bernadette-Mohr** [nschloe/tikzplotlib#299]
When specifying a colormap for my scatter plot, I get this error relating to the matplotlib2tikz code. It also occurs when I use matplotlib.cm.get_cmap() instead of seaborn.color_palette() and if I comment out the custom labels.
I don't see where 'mymap' is supposed to be set, did some line go missing in the axes.py code?

Edit: this works with version 0.6.8. Seems like there has been a lot of change, I couldn't find the cause of the error yet.

"MWE" is attached.
```
Traceback (most recent call last):
  File "/usr/data/mohrb/scripts/plot_DeltaG.py", line 245, in <module>
    matplotlib2tikz.save(sys.argv[2]+'.tex')#,
  File "/home/theorie/mohrb/anaconda3/envs/py36/lib/python3.6/site-packages/matplotlib2tikz/save.py", line 266, in save
    code = get_tikz_code(*args, filepath=filepath, **kwargs)
  File "/home/theorie/mohrb/anaconda3/envs/py36/lib/python3.6/site-packages/matplotlib2tikz/save.py", line 206, in get_tikz_code
    data, content = _recurse(data, figure)
  File "/home/theorie/mohrb/anaconda3/envs/py36/lib/python3.6/site-packages/matplotlib2tikz/save.py", line 362, in _recurse
    data, children_content = _recurse(data, child)
  File "/home/theorie/mohrb/anaconda3/envs/py36/lib/python3.6/site-packages/matplotlib2tikz/save.py", line 392, in _recurse
    data, cont = path.draw_pathcollection(data, child)
  File "/home/theorie/mohrb/anaconda3/envs/py36/lib/python3.6/site-packages/matplotlib2tikz/path.py", line 167, in draw_pathcollection
    mycolormap, is_custom_cmap = _mpl_cmap2pgf_cmap(obj.get_cmap(), data)
  File "/home/theorie/mohrb/anaconda3/envs/py36/lib/python3.6/site-packages/matplotlib2tikz/axes.py", line 618, in _mpl_cmap2pgf_cmap
    return _handle_listed_color_map(cmap, data)
  File "/home/theorie/mohrb/anaconda3/envs/py36/lib/python3.6/site-packages/matplotlib2tikz/axes.py", line 766, in _handle_listed_color_map
    colormap_string = "{mymap}{[1{}]\n {}\n}".format(unit, ";\n  ".join(colors))
KeyError: 'mymap'
```
```
import os
import sys
import matplotlib.pyplot as plt
import pandas as pd
import math
import matplotlib.lines as mlines
from matplotlib import rc
import seaborn as sns
import itertools
import matplotlib2tikz

sns.set_context('poster', font_scale=4)
sns.set(style='ticks')
sns.set_style({'xtick.direction': 'in', 'ytick.direction': 'in'})

colormap = sns.color_palette('Set1', n_colors=9)
```
```
#=================================================================================
#argv[1]: "/path/to/results.pickle"
#=================================================================================
table = pd.read_pickle(os.getcwd()+'/'+sys.argv[1])
data = pd.DataFrame()
headers = list(table)
lower_delim = 0.0
upper_delim = 0.0
idx = table.index 
colors = {}
shapes = {}
#=================================================================================
# Extract columns from dataframe for plotting
#=================================================================================

for name in headers:
    
    if '-substring' in name and name != 'this string':
        tmp = table[name]
        data[name] = tmp
        
        #get largest/smallest column entry for axis range
        if tmp.min() <= lower_delim:
            lower_delim = tmp.min()
        if tmp.max() >= upper_delim:
            upper_delim = tmp.max()
            
    elif name == 'important column':
        tmp = table[name]
        data[name] = tmp
        
#convert largest/smallest value to next bigger/smaller int
lower_delim = int(math.floor(lower_delim))
upper_delim = int(math.ceil(upper_delim))

#================================================================================
# Custom "switch" functionality
#================================================================================
class switch(object):
    def __init__(self, value):
        self.value = value
        self.fall = False

    def __iter__(self):
        #Return the case method once, then stop
        yield self.case
        raise StopIteration
    
    def case(self, *args):
        #empty case() is used as switch-"default"
        if self.fall or not args:
            return True
        elif args[0] in self.value or len(args) > 1 and args[1] in self.value:
            self.fall = True
            return True
        else:
            return False
#====================================================================
# set color and shape attributes to selected data groups:
#====================================================================
for i in idx:
    for case in switch(i):
        if case('-SN0-SNa-SC1-SC1', '-SNa-SN0-SC1-SC1'):
            colors[i] = colormap.colors[0]
            shapes[i] = '^'
            break
        if case('-SN0-SNa-SC2-SC2', '-SNa-SN0-SC2-SC2'):
            colors[i] = colormap.colors[1]
            shapes[i] = 'v'
            break
        if case('-SN0-SNa-SC5-SC5', '-SNa-SN0-SC5-SC5'):
            colors[i] = colormap.colors[2]
            shapes[i] = 'X'
            break
        if case('-SNda-SNda-SC1-SC2', '-SNda-SNda-SC2-SC1'):
            colors[i] = colormap.colors[3]
            shapes[i] = '<'
            break
        if case('-SNda-SNda-SC1-SC5', '-SNda-SNda-SC5-SC1'):
            colors[i] = colormap.colors[4]
            shapes[i] = '>'
            break
        if case('-SNda-SNda-SC2-SC5', '-SNda-SNda-SC5-SC2'):
            colors[i] = colormap.colors[5]
            shapes[i] = 'D'
            break
        if case('-SNda-SNda-SNa-SNd', '-SNda-SNda-SNd-SNa'):
            colors[i] = colormap.colors[6]#'#ffd92f'
            shapes[i] = 'p'
            break
        if case('-SNda-SNda-SNa-SNda', '-SNda-SNda-SNda-SNa'):
            colors[i] = colormap.colors[7]#'#ffd92f'
            shapes[i] = 'h'
            break
        if case('-SNda-SNda-SNd-SNda', '-SNda-SNda-SNda-SNd'):
            colors[i] = colormap.colors[8]
            shapes[i] = 'o'
            break
        if case():
            data = data[~data.index.str.contains(i)]
            
group = pd.Series(colors)
#=======================================================================================
# --------------------------------- Generating Plots ----------------------------------
#=======================================================================================

plt.rc('text', usetex=True)

plt.rcParams['mathtext.fontset'] = 'custom'
plt.rcParams['mathtext.rm'] = 'Liberation Sans Narrow'
plt.rcParams['mathtext.it'] = 'Liberation Sans:italic'
plt.rcParams['mathtext.bf'] = 'Liberation SansL:bold'

plt.rcParams['text.latex.preamble'] = [r'\boldmath']

data = data.reset_index()

fig = plt.figure()

ax = fig.add_subplot(111)

for n, g in data.groupby('indexgroup'):
    g.plot.scatter('group A', 'group B', marker=shapes[n], c=colors[n], s=60, ax=ax)
    
ax.set_xlim([lower_delim, upper_delim])
ax.set_ylim([lower_delim, upper_delim])

ax.plot(ax.get_xlim(), ax.get_ylim(), ls='-', c='.3', linewidth=1)

ax.set_xlabel(r"$\mathbf{Group A}$", fontsize=16)
ax.set_ylabel(r"$\mathbf{Group B}$", fontsize=16)

#============================================================================================================
# Custom marker labels:
# https://stackoverflow.com/questions/47391702/matplotlib-making-a-colored-markers-legend-from-scratch
#============================================================================================================
a = mlines.Line2D([], [], color=colormap[0], marker='^', linestyle='None', markersize=9, label='top Na/N0, sides C1')
b = mlines.Line2D([], [], color=colormap[1], marker='v', linestyle='None', markersize=9, label='top Na/N0, sides C2')
c = mlines.Line2D([], [], color=colormap[2], marker='X', linestyle='None', markersize=9, label='top Na/N0, sides C5')
d = mlines.Line2D([], [], color=colormap[3], marker='<', linestyle='None', markersize=9, label='top Nda, sides C1/C2')
e = mlines.Line2D([], [], color=colormap[4], marker='>', linestyle='None', markersize=9, label='top Nda, sides C1/C5')
f = mlines.Line2D([], [], color=colormap[5], marker='D', linestyle='None', markersize=9, label='top Nda, sides C2/C5')
g = mlines.Line2D([], [], color=colormap[6], marker='p', linestyle='None', markersize=9, label='top Nda, sides Na/Nd')
h = mlines.Line2D([], [], color=colormap[7], marker='h', linestyle='None', markersize=9, label='top Nda, sides Na/Nda')
i = mlines.Line2D([], [], color=colormap[8], marker='o', linestyle='None', markersize=9, label='top Nda, sides Nd/Nda')

ax.legend(handles=[a, b, c, d, e, f, g, h, i], fontsize=14, loc=4)

plt.tight_layout()
#fig.savefig(sys.argv[2]+'.png', dpi=300)
fig.savefig(sys.argv[2] + '.pdf')
matplotlib2tikz.save(sys.argv[2]+'.tex',
           figureheight = '\\figureheight',
           figurewidth = '\\figurewidth'
           #extra_axis_parameters={
                ##'x tick label text width={\\textwidth}'
                #'x tick label text width',
                #'10 pt'
            #},
         )
#plt.show()
```

[test.pdf](https://github.com/nschloe/matplotlib2tikz/files/3172758/test.pdf)

**Comment by jvytee** [comment]
If you happen to experience the same `KeyError` due to `mymap` in 0.8.1, I think #316 fixes exactly this (thanks!).

**Comment by nschloe** [comment]
Okay, tentatively closing.

@Bernadette-Mohr Feel free to use triple fences for code blocks next time. ```
Also, try to keep your examplex _minimal_. Nobody wants to plow through dozens of lines of code.
