### ISSUE TITLE
error with ydata_mask in line2d.py

### ISSUE THREAD

**Issue by Mettphysik** [nschloe/tikzplotlib#309]
Hello,

I just discovered tikzplotlib and like it a lot. Unfortunately an error is sometimes occuring when trying to do the following in python (using spyder, dont know if this is important):
```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Data=np.array([[0,28,56,84,112],[5.0,7.0,9.0,12.0,15.0]])
Data=Data.transpose()
fig=plt.figure(1,figsize=(7,7))    
Table=pd.DataFrame(Data,columns=["Abstand in mm","Serie 1"])
plt.errorbar(Table["Abstand in mm"], Table["Serie 1"],yerr=1.0,fmt="o",color="black")     
plt.xlabel("Schichtabstand [mm]")
plt.ylabel("Lagedifferenz [mm]")
plt.legend(loc="upper left")

import tikzplotlib
tikzplotlib.save(filepath="graphi.tex")
```

The following error occurs and no texcode was created:
```
Traceback (most recent call last):

  File "<ipython-input-17-9d95a62cff74>", line 1, in <module>
    runfile('C:/Users/Baul/Documents/Uni/Master/Python/MR/mplStyletest.py', wdir='C:/Users/Baul/Documents/Uni/Master/Python/MR')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Baul/Documents/Uni/Master/Python/MR/mplStyletest.py", line 45, in <module>
    tikzplotlib.save(filepath="graphi.tex")

  File "C:\ProgramData\Anaconda3\lib\site-packages\tikzplotlib\save.py", line 257, in save
    code = get_tikz_code(*args, filepath=filepath, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tikzplotlib\save.py", line 197, in get_tikz_code
    data, content = _recurse(data, figure)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tikzplotlib\save.py", line 349, in _recurse
    data, children_content = _recurse(data, child)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tikzplotlib\save.py", line 365, in _recurse
    data, cont = line2d.draw_line2d(data, child)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tikzplotlib\line2d.py", line 73, in draw_line2d
    c, axis_options = _table(obj, data)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tikzplotlib\line2d.py", line 314, in _table
    if any(ydata_mask): 

TypeError: 'method' object is not iterable
```

Now I went to the file causing the error (line2d.py) and changed ydata_mask to the previously defined ydata_alt. After this, everything works fine for me. I am no expert, so I wonder what are the consequences of this change? I guess different errors might be raised?

Also, in the same file exists a TODO regarding masks, so this whole thing here might help you in the future.

**Comment by nschloe** [comment]
Thanks for the example code, I could easily fix that.
