### ISSUE TITLE
tikzplotlib with matplotlib 3.8.* not working

### ISSUE THREAD

**Issue by annabeckers** [nschloe/tikzplotlib#596]
When using matplotlib 3.8.* tikzplotlib is throwing an error when its getting imported.

common_texification got removed with matplotlib 3.8.0 and can therefore not be found: https://fossies.org/linux/matplotlib/doc/api/prev_api_changes/api_changes_3.8.0/removals.rst

Minimum (non)-working example:
```
from matplotlib import pyplot as plt
import tikzplotlib
```
Error:
Traceback (most recent call last):
  File "/home/random/Bachelor/project/analyze.py", line 5, in <module>
    from src.analyzer import Analyzer
  File "/home/random/Bachelor/project/src/analyzer.py", line 20, in <module>
    import tikzplotlib
  File "/home/random/Bachelor/project/.venv/lib/python3.10/site-packages/tikzplotlib/__init__.py", line 5, in <module>
    from ._save import Flavors, get_tikz_code, save
  File "/home/random/Bachelor/project/.venv/lib/python3.10/site-packages/tikzplotlib/_save.py", line 11, in <module>
    from . import _axes
  File "/home/random/Bachelor/project/.venv/lib/python3.10/site-packages/tikzplotlib/_axes.py", line 3, in <module>
    from matplotlib.backends.backend_pgf import (
ImportError: cannot import name 'common_texification' from 'matplotlib.backends.backend_pgf' (/home/random/Bachelor/project/.venv/lib/python3.10/site-packages/matplotlib/backends/backend_pgf.py)

**Comment by annabeckers** [comment]
The search function would not show the other issue pertaining to this problem: https://github.com/nschloe/tikzplotlib/issues/559

**Comment by FriedrichFroebel** [comment]
Duplicate of #559.
