### ISSUE TITLE
Tikzplotlib not compatible with newest version of Matplotlib anymore

### ISSUE THREAD

**Issue by fjakob** [nschloe/tikzplotlib#622]
Hello,

after normally installing numpy, matplotlib, etc (without any specifications, so just the latest versions), it fails already to import the tikzplotlib module.

I.e.: `import tikzplotlib` after `import matplotlib` leads to the error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\fjako\anaconda3\Lib\site-packages\tikzplotlib\__init__.py", line 5, in <module>
    from ._save import Flavors, get_tikz_code, save
  File "C:\Users\fjako\anaconda3\Lib\site-packages\tikzplotlib\_save.py", line 11, in <module>
    from . import _axes
  File "C:\Users\fjako\anaconda3\Lib\site-packages\tikzplotlib\_axes.py", line 3, in <module>
    from matplotlib.backends.backend_pgf import (
ImportError: cannot import name 'common_texification' from 'matplotlib.backends.backend_pgf' (C:\Users\fjako\anaconda3\Lib\site-packages\matplotlib\backends\backend_pgf.py)

It would be nice if the package can be made compatible with the state of the art. Thanks a lot!

**Comment by nschloe** [comment]
> It would be nice if the package can be made compatible with the state of the art.

It'd be super nice! Will do when I have time.
